services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duduProject
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./config/jwt:/var/www/html/config/jwt
    ports:
      - "8080:80"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - symfony_network
    environment:
      - DATABASE_URL=postgresql://root:root@postgresql:5432/duduProject?serverVersion=16&charset=utf8
    command: >
      bash -c "
        mkdir -p config/jwt &&
        if [ -f config/jwt/private.pem ]; then chmod 600 config/jwt/private.pem; fi &&
        if [ -f config/jwt/public.pem ]; then chmod 644 config/jwt/public.pem; fi &&
        composer install &&
        php bin/console cache:clear &&
        a2enmod rewrite &&
        a2enmod headers &&
        service apache2 restart &&
        symfony serve --no-tls --allow-all-ip"

  postgresql:
    image: postgres:16-alpine
    container_name: symfony_db_duduProject
    restart: unless-stopped
    environment:
      POSTGRES_DB: duduProject
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - symfony_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgresql
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
    driver: local