services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duduProject
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./config/jwt:/var/www/html/config/jwt
      - /var/www/html/var/cache
    ports:
      - "8000:8000"  # Port modifié pour correspondre au serveur Symfony
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - symfony_network
    environment:
      - DATABASE_URL=postgresql://root:root@postgresql:5432/duduProject?serverVersion=16&charset=utf8
    command: >
      bash -c "
        pkill -f 'symfony serve' || true &&
        symfony server:stop
        composer install &&
        rm -rf var/cache/* &&
        php bin/console cache:clear &&
        php bin/console cache:warmup &&
        symfony serve --port=8000 --no-tls --allow-all-ip"

  postgresql:
    image: postgres:16-alpine
    container_name: symfony_db_duduProject
    restart: unless-stopped
    environment:
      POSTGRES_DB: duduProject
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - symfony_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d duduProject"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgresql
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
    driver: local